inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "spec/generators/tmp/**/*"
    - "spec/dummy/db/*"
    - "spec/dummy/config/*"
    - "Dangerfile"
    - "gemfiles/*.gemfile"

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/doorkeeper/rake/*
    - doorkeeper.gemspec

Metrics/MethodLength:
  Exclude:
    - spec/dummy/db/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  MinSize: 3
Style/WordArray:
  MinSize: 3

Style/ClassAndModuleChildren:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/TrailingEmptyLines:
  Enabled: true
Layout/DotPosition:
  EnforcedStyle: leading
Layout/LineLength:
  Exclude:
    - spec/**/*
  Max: 100

Rails/HttpPositionalArguments:
  Exclude:
    - spec/grape/*
Rails/HttpStatus:
  Enabled: false
Rails/RakeEnvironment:
  Exclude:
    - Rakefile
Rails/ReflectionClassName:
  Exclude:
    - 'lib/doorkeeper/orm/active_record/mixins/access_grant.rb'
    - 'lib/doorkeeper/orm/active_record/mixins/access_token.rb'
    - 'lib/doorkeeper/orm/active_record/mixins/application.rb'
Rails/SkipsModelValidations:
  Enabled: false
